export enum ProfileVisibility {
  PUBLIC = "PUBLIC",
  PRIVATE = "PRIVATE",
}

export enum OrganizationType {
  CORPORATE = "CORPORATE",
  ANGEL_NETWORK = "ANGEL_NETWORK",
  VENTURE_CAPITAL = "VENTURE_CAPITAL",
  FOUNDATION = "FOUNDATION",
  NGO = "NGO",
  GOVERNMENT_AGENCY = "GOVERNMENT_AGENCY",
  UNIVERSITY = "UNIVERSITY",
  RESEARCH_INSTITUTION = "RESEARCH_INSTITUTION",
  INCUBATOR = "INCUBATOR",
  ACCELERATOR = "ACCELERATOR",
  DIASPORA_GROUP = "DIASPORA_GROUP",
  PHILANTHROPIST = "PHILANTHROPIST",
  OTHER = "OTHER",
}

export enum SponsorMembershipRole {
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  MEMBER = "MEMBER",
}

export enum SponsorMembershipStatus {
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  REMOVED = "REMOVED",
}

export enum SponsorVerificationStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  CHANGES_REQUESTED = "CHANGES_REQUESTED",
  VERIFIED = "VERIFIED",
  REJECTED = "REJECTED",
  SUSPENDED = "SUSPENDED",
}

export enum InnovationStage {
  IDEA = "IDEA",
  RESEARCH = "RESEARCH",
  PROTOTYPE = "PROTOTYPE",
  PILOT = "PILOT",
  EARLY_REVENUE = "EARLY_REVENUE",
  GROWTH = "GROWTH",
  SCALING = "SCALING",
}

export enum PitchStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  CHANGES_REQUESTED = "CHANGES_REQUESTED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  WITHDRAWN = "WITHDRAWN",
  ARCHIVED = "ARCHIVED",
}

export enum FileUploadStatus {
  PENDING_UPLOAD = "PENDING_UPLOAD",
  UPLOADED = "UPLOADED",
  PENDING_SCAN = "PENDING_SCAN",
  AVAILABLE = "AVAILABLE",
  REJECTED = "REJECTED",
  DELETED = "DELETED",
}

export enum FileScanStatus {
  PENDING = "PENDING",
  SCANNING = "SCANNING",
  CLEAN = "CLEAN",
  INFECTED = "INFECTED",
  FAILED = "FAILED",
  SKIPPED = "SKIPPED",
}

export enum DocumentPurpose {
  PITCH_DECK = "PITCH_DECK",
  PITCH_BUSINESS_PLAN = "PITCH_BUSINESS_PLAN",
  PITCH_FINANCIAL_MODEL = "PITCH_FINANCIAL_MODEL",
  PITCH_PROTOTYPE_IMAGE = "PITCH_PROTOTYPE_IMAGE",
  PITCH_SUPPORTING_EVIDENCE = "PITCH_SUPPORTING_EVIDENCE",
  SPONSOR_REGISTRATION_CERT = "SPONSOR_REGISTRATION_CERT",
  SPONSOR_PROOF_OF_ADDRESS = "SPONSOR_PROOF_OF_ADDRESS",
  SPONSOR_TAX_EVIDENCE = "SPONSOR_TAX_EVIDENCE",
  SPONSOR_LETTER_OF_AUTHORITY = "SPONSOR_LETTER_OF_AUTHORITY",
}

export enum ReviewAssignmentStatus {
  ASSIGNED = "ASSIGNED",
  ACCEPTED = "ACCEPTED",
  DECLINED = "DECLINED",
  COMPLETED = "COMPLETED",
  REVOKED = "REVOKED",
}

export enum ConflictStatus {
  NOT_DECLARED = "NOT_DECLARED",
  NO_CONFLICT = "NO_CONFLICT",
  POTENTIAL_CONFLICT = "POTENTIAL_CONFLICT",
  CONFIRMED_CONFLICT = "CONFIRMED_CONFLICT",
}

export enum ReviewRecommendation {
  APPROVE = "APPROVE",
  REQUEST_CHANGES = "REQUEST_CHANGES",
  REJECT = "REJECT",
}

export const REVIEW_CRITERIA = [
  "problemClarity",
  "solutionQuality",
  "feasibility",
  "innovation",
  "marketNeed",
  "teamCapability",
  "traction",
  "impact",
  "scalability",
  "fundingReadiness",
] as const;

export type ReviewCriterion = (typeof REVIEW_CRITERIA)[number];

export const STAGE3_ERROR_CODES = {
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INCOMPLETE_PROFILE: "INCOMPLETE_PROFILE",
  INCOMPLETE_PITCH: "INCOMPLETE_PITCH",
  INVALID_TRANSITION: "INVALID_TRANSITION",
  CONFLICT_VERSION: "CONFLICT_VERSION",
  FILE_NOT_AVAILABLE: "FILE_NOT_AVAILABLE",
  FILE_REJECTED: "FILE_REJECTED",
  RATE_LIMITED: "RATE_LIMITED",
  CONFLICT_DECLARED: "CONFLICT_DECLARED",
  NOT_VERIFIED: "NOT_VERIFIED",
} as const;
