export const NIGERIAN_STATES = [
  { code: "AB", name: "Abia", region: "South East" },
  { code: "AD", name: "Adamawa", region: "North East" },
  { code: "AK", name: "Akwa Ibom", region: "South South" },
  { code: "AN", name: "Anambra", region: "South East" },
  { code: "BA", name: "Bauchi", region: "North East" },
  { code: "BY", name: "Bayelsa", region: "South South" },
  { code: "BE", name: "Benue", region: "North Central" },
  { code: "BO", name: "Borno", region: "North East" },
  { code: "CR", name: "Cross River", region: "South South" },
  { code: "DE", name: "Delta", region: "South South" },
  { code: "EB", name: "Ebonyi", region: "South East" },
  { code: "ED", name: "Edo", region: "South South" },
  { code: "EK", name: "Ekiti", region: "South West" },
  { code: "EN", name: "Enugu", region: "South East" },
  { code: "FC", name: "Federal Capital Territory", region: "North Central" },
  { code: "GO", name: "Gombe", region: "North East" },
  { code: "IM", name: "Imo", region: "South East" },
  { code: "JI", name: "Jigawa", region: "North West" },
  { code: "KD", name: "Kaduna", region: "North West" },
  { code: "KN", name: "Kano", region: "North West" },
  { code: "KT", name: "Katsina", region: "North West" },
  { code: "KE", name: "Kebbi", region: "North West" },
  { code: "KO", name: "Kogi", region: "North Central" },
  { code: "KW", name: "Kwara", region: "North Central" },
  { code: "LA", name: "Lagos", region: "South West" },
  { code: "NA", name: "Nasarawa", region: "North Central" },
  { code: "NI", name: "Niger", region: "North Central" },
  { code: "OG", name: "Ogun", region: "South West" },
  { code: "ON", name: "Ondo", region: "South West" },
  { code: "OS", name: "Osun", region: "South West" },
  { code: "OY", name: "Oyo", region: "South West" },
  { code: "PL", name: "Plateau", region: "North Central" },
  { code: "RI", name: "Rivers", region: "South South" },
  { code: "SO", name: "Sokoto", region: "North West" },
  { code: "TA", name: "Taraba", region: "North East" },
  { code: "YO", name: "Yobe", region: "North East" },
  { code: "ZA", name: "Zamfara", region: "North West" },
] as const;

export const INNOVATION_SECTORS = [
  {
    slug: "agriculture-agritech",
    name: "Agriculture & AgriTech",
    description: "Farm innovation, food security, and agricultural technology",
    sortOrder: 1,
  },
  {
    slug: "fintech",
    name: "FinTech & Financial Services",
    description: "Digital banking, payments, and inclusive finance",
    sortOrder: 2,
  },
  {
    slug: "healthtech-biotech",
    name: "HealthTech & Biotech",
    description: "Healthcare delivery, diagnostics, and life sciences",
    sortOrder: 3,
  },
  {
    slug: "edtech",
    name: "EdTech & Learning",
    description: "Education platforms, skills development, and training",
    sortOrder: 4,
  },
  {
    slug: "energy-cleantech",
    name: "Energy & CleanTech",
    description: "Renewable energy, power solutions, and sustainability",
    sortOrder: 5,
  },
  {
    slug: "logistics-supply-chain",
    name: "Logistics & Supply Chain",
    description: "Transport, warehousing, and distribution innovation",
    sortOrder: 6,
  },
  {
    slug: "manufacturing-industry",
    name: "Manufacturing & Industry 4.0",
    description: "Industrial automation, production, and hardware",
    sortOrder: 7,
  },
  {
    slug: "creative-economy",
    name: "Creative Economy & Media",
    description: "Film, music, design, content, and cultural innovation",
    sortOrder: 8,
  },
  {
    slug: "proptech",
    name: "Real Estate & PropTech",
    description: "Housing, construction tech, and property management",
    sortOrder: 9,
  },
  {
    slug: "govtech-civic",
    name: "GovTech & Civic Innovation",
    description: "Public service delivery and civic engagement tools",
    sortOrder: 10,
  },
  {
    slug: "climate-sustainability",
    name: "Climate & Sustainability",
    description: "Environmental protection and green economy solutions",
    sortOrder: 11,
  },
  {
    slug: "security-defence",
    name: "Security & Defence Tech",
    description: "Safety, surveillance, and national security innovation",
    sortOrder: 12,
  },
  {
    slug: "telecom-connectivity",
    name: "Telecom & Connectivity",
    description: "Network infrastructure and communication technology",
    sortOrder: 13,
  },
  {
    slug: "ai-data-science",
    name: "AI & Data Science",
    description: "Machine learning, analytics, and intelligent systems",
    sortOrder: 14,
  },
  {
    slug: "retail-ecommerce",
    name: "Retail & E-commerce",
    description: "Marketplaces, commerce platforms, and consumer tech",
    sortOrder: 15,
  },
  {
    slug: "tourism-hospitality",
    name: "Tourism & Hospitality",
    description: "Travel, hospitality, and experience innovation",
    sortOrder: 16,
  },
] as const;

export const SYSTEM_ROLES = [
  {
    type: "SUPER_ADMIN" as const,
    name: "Super Administrator",
    description: "Full platform administration access",
  },
  {
    type: "NATIONAL_ADMIN" as const,
    name: "National Administrator",
    description: "National-level platform administration",
  },
  {
    type: "STATE_ADMIN" as const,
    name: "State Administrator",
    description: "State-level platform administration",
  },
  {
    type: "REVIEWER" as const,
    name: "Reviewer",
    description: "Reviews and evaluates innovation submissions",
  },
  {
    type: "INNOVATOR" as const,
    name: "Innovator",
    description: "Submits and manages innovation pitches",
  },
  {
    type: "SPONSOR" as const,
    name: "Sponsor",
    description: "Discovers and supports innovations",
  },
  {
    type: "MENTOR" as const,
    name: "Mentor",
    description: "Guides innovators through the platform",
  },
] as const;
